In [ ]:
import pandas as pd
import numpy as np

In [219]:
from google.colab import files
files.upload()
df = pd.read_csv("electricity.csv")

Saving electricity.csv to electricity (13).csv

In [220]:
df.head()

,household_id,household_size,rooms,appliances,temp_c,income,electricity_kwh,high_usage
0,1,2,2,4,18,28000,95,0
1,2,3,3,6,20,35000,125,0
2,3,4,3,8,22,42000,160,0
3,4,5,4,10,24,48000,205,1
4,5,6,4,12,25,52000,235,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   household_id     30 non-null     int64
 1   household_size   30 non-null     int64
 2   rooms            30 non-null     int64
 3   appliances       30 non-null     int64
 4   temp_c           30 non-null     int64
 5   income           30 non-null     int64
 6   electricity_kwh  30 non-null     int64
 7   high_usage       30 non-null     int64
dtypes: int64(8)
memory usage: 2.0 KB

In [213]:
df.describe()

,household_id,household_size,rooms,appliances,temp_c,income,electricity_kwh,high_usage
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,15.500000,3.866667,3.400000,8.533333,23.000000,42566.666667,176.166667,0.466667
std,8.803408,1.716720,1.069966,3.636343,3.129393,10785.313556,70.925937,0.507416
min,1.000000,1.000000,1.000000,3.000000,17.000000,25000.000000,70.000000,0.000000
25%,8.250000,2.250000,3.000000,5.250000,21.000000,33500.000000,116.250000,0.000000
50%,15.500000,4.000000,3.000000,8.000000,23.000000,42500.000000,162.500000,0.000000
75%,22.750000,5.000000,4.000000,11.000000,25.750000,50000.000000,222.500000,1.000000
max,30.000000,7.000000,5.000000,16.000000,28.000000,65000.000000,325.000000,1.000000

In [ ]:
df.isnull().sum()

household_id       0
household_size     0
rooms              0
appliances         0
temp_c             0
income             0
electricity_kwh    0
high_usage         0
dtype: int64

# First we need to perform EDA then, modeling

### Now, we need to seperate the our independent feature variables and dependent target variables

In [ ]:
y = df['electricity_kwh']

In [ ]:
X = df[['household_size',
        'rooms',
        'appliances',
        'temp_c',
        'income']]

## Step 1: split data into train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.3,random_state=42)

In [ ]:
X_train.shape, X_test.shape

((21, 5), (9, 5))

# Step 2 : Standard scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 3: Fitting the Model

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train_scaled, y_train)

LinearRegression()

In [ ]:
y_predict = model.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import r2_score
R_square = r2_score(y_test, y_predict)
print(f"the r2 is : {R_square}")

the r2 is : 0.9908862633033365